//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_HOA_DON
    {
        public int ID_CHI_TIET_HOA_DON { get; set; }
        public Nullable<int> ID_DON_DAT_PHONG { get; set; }
        public Nullable<int> ID_KHACH_HANG { get; set; }
        public string TEN_PHONG { get; set; }
        public Nullable<int> ID_CHI_TIET_DICH_VU { get; set; }
        public Nullable<int> TIENPHONG { get; set; }
        public Nullable<int> TIENDICHVU { get; set; }
        public Nullable<int> TONGTIEN { get; set; }
        public Nullable<System.DateTime> NGAYXUATHOADON { get; set; }
        public string MANHANVIEN { get; set; }
    
        public virtual CHI_TIET_DICH_VU CHI_TIET_DICH_VU { get; set; }
        public virtual DON_DAT_PHONG DON_DAT_PHONG { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
