//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIEU
    {
        public int ID_CHI_TIET_CHI_TIEU { get; set; }
        public string TENHANG { get; set; }
        public string DONVITINH { get; set; }
        public Nullable<int> GIA { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> THANHTIEN { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
    }
}
