//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_VAT_TU
    {
        public int ID { get; set; }
        public Nullable<int> MA_VAT_TU { get; set; }
        public Nullable<int> ID_LOAI_PHONG { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string TINHTRANG { get; set; }
    
        public virtual LOAI_PHONG LOAI_PHONG { get; set; }
        public virtual VAT_TU VAT_TU { get; set; }
    }
}
