//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICH_VU
    {
        public DICH_VU()
        {
            this.CHI_TIET_DICH_VU = new HashSet<CHI_TIET_DICH_VU>();
        }
    
        public int ID_DICH_VU { get; set; }
        public string TENDICHVU { get; set; }
        public Nullable<int> GIA { get; set; }
        public string TINHTRANG { get; set; }
    
        public virtual ICollection<CHI_TIET_DICH_VU> CHI_TIET_DICH_VU { get; set; }
    }
}
