//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAI_PHONG
    {
        public LOAI_PHONG()
        {
            this.CHI_TIET_VAT_TU = new HashSet<CHI_TIET_VAT_TU>();
            this.PHONGs = new HashSet<PHONG>();
        }
    
        public int ID_LOAI_PHONG { get; set; }
        public string TENLOAIPHONG { get; set; }
        public Nullable<int> GIA { get; set; }
        public Nullable<int> SOGIUONG { get; set; }
    
        public virtual ICollection<CHI_TIET_VAT_TU> CHI_TIET_VAT_TU { get; set; }
        public virtual ICollection<PHONG> PHONGs { get; set; }
    }
}
