//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLKhachSanDBContext : DbContext
    {
        public QLKhachSanDBContext()
            : base("name=QLKhachSanDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CHI_TIET_DICH_VU> CHI_TIET_DICH_VU { get; set; }
        public DbSet<CHI_TIET_HOA_DON> CHI_TIET_HOA_DON { get; set; }
        public DbSet<CHI_TIET_VAT_TU> CHI_TIET_VAT_TU { get; set; }
        public DbSet<CHI_TIEU> CHI_TIEU { get; set; }
        public DbSet<DICH_VU> DICH_VU { get; set; }
        public DbSet<DON_DAT_PHONG> DON_DAT_PHONG { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<LOAI_PHONG> LOAI_PHONG { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<PHONG> PHONGs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<VAT_TU> VAT_TU { get; set; }
    }
}
