//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAT_TU
    {
        public VAT_TU()
        {
            this.CHI_TIET_VAT_TU = new HashSet<CHI_TIET_VAT_TU>();
        }
    
        public int MA_VAT_TU { get; set; }
        public string TENVATTU { get; set; }
        public Nullable<int> DONGIA { get; set; }
    
        public virtual ICollection<CHI_TIET_VAT_TU> CHI_TIET_VAT_TU { get; set; }
    }
}
